#change_language.py:

def change_language(language):
    translations = {
        "en": {
            "source": "Source file:",
            "target": "Target file:",
            "browse": "Browse...",
            "convert": "Convert",
            "repair": "Repair video",
            "info": "Show video information",
            "extract_audio": "Extract audio",
            "split_video": "Split video",
            "cut_segment": "Cut segment",
            "download": "Download",
            "video_options": "Video options:",
            "speed": "Change speed (factor)",
            "mirror": "Mirror video",
            "split_duration": "Split video (in seconds):",
            "audio_extract": "Extract audio:",
            "segment_extract": "Extract segment / Start and end time (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Main",
            "youtube_tab": "Video download",
            "language_tab": "Language",
            "error_ffmpeg": "ffmpeg or ffprobe is not available. Please install ffmpeg from:",
            "error_download_ffmpeg": "Error downloading and installing ffmpeg:",
            "error_ffmpeg_command": "Error executing ffmpeg command:",
            "error_select_source_target": "Please select a source and a target.",
            "error_extraction": "Error extracting:",
            "success_conversion": "File successfully converted.",
            "success_repair": "Video successfully copied (small errors may be fixed).",
            "success_segment": "Segment successfully cut.",
            "success_audio_extraction": "Audio successfully extracted.",
            "success_video_split": "Video successfully split into {num_segments} parts.",
            "success_youtube_download": "YouTube video successfully downloaded.",
            "error_video_duration": "Invalid video duration.",
            "error_split": "Error splitting the video:",
            "error_select_file": "Please select a source file.",
            "error_no_url": "Please enter a URL.",
            "update_available": "A new version ({latest_version}) is available. Changes:\n{changes}\n\nDo you want to update?",
            "update_aborted": "The update was aborted.",
            "success": "No updates available",
            "check_update": "Check for updates",
            "info_tab": "Info",
            "error": "Error",
            "url": "URL",
            "success_download": "Download successful: {filename}"
        },
        "es": {
            "source": "Archivo Fuente:",
            "target": "Archivo Destino:",
            "browse": "Buscar...",
            "convert": "Convertir",
            "repair": "Reparar Video",
            "info": "Mostrar Información del Video",
            "extract_audio": "Extraer Audio",
            "split_video": "Dividir Video",
            "cut_segment": "Cortar Segmento",
            "download": "Descargar",
            "video_options": "Opciones de Video:",
            "speed": "Cambiar Velocidad (Factor)",
            "mirror": "Espejar Video",
            "split_duration": "Dividir Video (en segundos):",
            "audio_extract": "Extraer Audio:",
            "segment_extract": "Extraer Segmento / Hora de Inicio y Hora de Fin (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Principal",
            "youtube_tab": "Descarga de Video",
            "language_tab": "Idioma",
            "error_ffmpeg": "ffmpeg o ffprobe no está disponible. Instale ffmpeg desde:",
            "error_download_ffmpeg": "Error al descargar e instalar ffmpeg:",
            "error_ffmpeg_command": "Error al ejecutar ffmpeg:",
            "error_select_source_target": "Seleccione una fuente y un destino.",
            "error_extraction": "Error al extraer:",
            "success_conversion": "Archivo convertido con éxito.",
            "success_repair": "Video copiado con éxito (se pueden corregir pequeños errores).",
            "success_segment": "Segmento cortado con éxito.",
            "success_audio_extraction": "Audio extraído con éxito.",
            "success_video_split": "Video dividido con éxito en {num_segments} partes.",
            "success_youtube_download": "Video de YouTube descargado con éxito.",
            "error_video_duration": "Duración de video no válida.",
            "error_split": "Error al dividir el video:",
            "error_select_file": "Seleccione un archivo fuente.",
            "error_no_url": "Ingrese una URL.",
            "update_available": "Una nueva versión ({latest_version}) está disponible. Cambios:\n{changes}\n\n¿Quieres actualizar?",
            "update_aborted": "La actualización fue abortada.",
            "success": "No hay actualizaciones disponibles",
            "check_update": "Buscar actualizaciones",
            "info_tab": "Información",
            "error": "Error",
            "url": "URL",
            "success_download": "Descarga exitosa: {filename}"
        },
        "de": {
            "source": "Quelldatei:",
            "target": "Zieldatei:",
            "browse": "Durchsuchen...",
            "convert": "Konvertieren",
            "repair": "Video reparieren",
            "info": "Videoinformationen anzeigen",
            "extract_audio": "Audio extrahieren",
            "split_video": "Video teilen",
            "cut_segment": "Segment schneiden",
            "download": "Herunterladen",
            "video_options": "Videooptionen:",
            "speed": "Geschwindigkeit ändern (Faktor)",
            "mirror": "Video spiegeln",
            "split_duration": "Video teilen (in Sekunden):",
            "audio_extract": "Audio extrahieren:",
            "segment_extract": "Segment extrahieren / Start- und Endzeit (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Haupt",
            "youtube_tab": "Video-Download",
            "language_tab": "Sprache",
            "error_ffmpeg": "ffmpeg oder ffprobe ist nicht verfügbar. Bitte ffmpeg von hier installieren:",
            "error_download_ffmpeg": "Fehler beim Herunterladen und Installieren von ffmpeg:",
            "error_ffmpeg_command": "Fehler beim Ausführen des ffmpeg-Befehls:",
            "error_select_source_target": "Bitte wählen Sie eine Quelle und ein Ziel.",
            "error_extraction": "Fehler beim Extrahieren:",
            "success_conversion": "Datei erfolgreich konvertiert.",
            "success_repair": "Video erfolgreich kopiert (kleine Fehler könnten behoben sein).",
            "success_segment": "Segment erfolgreich geschnitten.",
            "success_audio_extraction": "Audio erfolgreich extrahiert.",
            "success_video_split": "Video erfolgreich in {num_segments} Teile geteilt.",
            "success_youtube_download": "YouTube Video erfolgreich heruntergeladen.",
            "error_video_duration": "Ungültige Videodauer.",
            "error_split": "Fehler beim Teilen des Videos:",
            "error_select_file": "Bitte wählen Sie eine Quelldatei.",
            "error_no_url": "Bitte geben Sie eine URL ein.",
            "update_available": "Eine neue Version ({latest_version}) ist verfügbar. Änderungen:\n{changes}\n\nMöchten Sie aktualisieren?",
            "update_aborted": "Das Update wurde abgebrochen.",
            "success": "Keine Updates verfügbar",
            "check_update": "Auf Updates prüfen",
            "info_tab": "Info",
            "error": "Fehler",
            "url": "URL",
            "success_download": "Download erfolgreich: {filename}"
        },
        "it": {
            "source": "File sorgente:",
            "target": "File di destinazione:",
            "browse": "Sfoglia...",
            "convert": "Converti",
            "repair": "Ripara video",
            "info": "Mostra informazioni video",
            "extract_audio": "Estrai audio",
            "split_video": "Dividi video",
            "cut_segment": "Taglia segmento",
            "download": "Scarica",
            "video_options": "Opzioni video:",
            "speed": "Cambia velocità (fattore)",
            "mirror": "Specchio Video",
            "split_duration": "Dividi video (in secondi):",
            "audio_extract": "Estrai audio:",
            "segment_extract": "Estrai segmento / Ora di inizio e fine (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Principale",
            "youtube_tab": "Download Video",
            "language_tab": "Lingua",
            "error_ffmpeg": "ffmpeg o ffprobe non è disponibile. Installa ffmpeg da:",
            "error_download_ffmpeg": "Errore durante il download e l'installazione di ffmpeg:",
            "error_ffmpeg_command": "Errore durante l'esecuzione di ffmpeg:",
            "error_select_source_target": "Seleziona una fonte e un obiettivo.",
            "error_extraction": "Errore durante l'estrazione:",
            "success_conversion": "File convertito con successo.",
            "success_repair": "Video copiato con successo (possono essere corretti piccoli errori).",
            "success_segment": "Segmento tagliato con successo.",
            "success_audio_extraction": "Audio estratto con successo.",
            "success_video_split": "Video diviso con successo in {num_segments} parti.",
            "success_youtube_download": "Video di YouTube scaricato con successo.",
            "error_video_duration": "Durata video non valida.",
            "error_split": "Errore durante la divisione del video:",
            "error_select_file": "Seleziona un file sorgente.",
            "error_no_url": "Inserisci un URL.",
            "update_available": "È disponibile una nuova versione ({latest_version}). Modifiche:\n{changes}\n\nVuoi aggiornare?",
            "update_aborted": "L'aggiornamento è stato annullato.",
            "info_tab": "Info",
            "check_update": "Controlla aggiornamenti",
            "success": "Operazione completata con successo",
            "error": "Errore",
            "url": "URL",
            "success_download": "Download riuscito: {filename}"        
        },
        "fr": {
            "source": "Fichier source:",
            "target": "Fichier cible:",
            "browse": "Parcourir...",
            "convert": "Convertir",
            "repair": "Réparer la vidéo",
            "info": "Afficher les informations vidéo",
            "extract_audio": "Extraire l'audio",
            "split_video": "Diviser la vidéo",
            "cut_segment": "Couper le segment",
            "download": "Télécharger",
            "video_options": "Options vidéo:",
            "speed": "Modifier la vitesse (facteur)",
            "mirror": "Miroir vidéo",
            "split_duration": "Diviser la vidéo (en secondes):",
            "audio_extract": "Extraire l'audio:",
            "segment_extract": "Extraire le segment / Heure de début et de fin (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Principal",
            "youtube_tab": "Téléchargement de vidéo",
            "language_tab": "Langue",
            "error_ffmpeg": "ffmpeg ou ffprobe n'est pas disponible. Veuillez installer ffmpeg depuis:",
            "error_download_ffmpeg": "Erreur lors du téléchargement et de l'installation de ffmpeg:",
            "error_ffmpeg_command": "Erreur lors de l'exécution de la commande ffmpeg:",
            "error_select_source_target": "Veuillez sélectionner une source et une cible.",
            "error_extraction": "Erreur d'extraction:",
            "success_conversion": "Fichier converti avec succès.",
            "success_repair": "Vidéo copiée avec succès (des petites erreurs peuvent être corrigées).",
            "success_segment": "Segment coupé avec succès.",
            "success_audio_extraction": "Audio extrait avec succès.",
            "success_video_split": "Vidéo divisée avec succès en {num_segments} parties.",
            "success_youtube_download": "Vidéo YouTube téléchargée avec succès.",
            "error_video_duration": "Durée de la vidéo non valide.",
            "error_split": "Erreur lors de la division de la vidéo:",
            "error_select_file": "Veuillez sélectionner un fichier source.",
            "error_no_url": "Veuillez entrer une URL.",
            "update_available": "Une nouvelle version ({latest_version}) est disponible. Modifications:\n{changes}\n\nVoulez-vous mettre à jour?",
            "update_aborted": "La mise à jour a été annulée.",
            "success": "Pas de mises à jour disponibles",
            "check_update": "Vérifier les mises à jour",
            "info_tab": "Information",
            "error": "Erreur",
            "url": "URL",
            "success_download": "Téléchargement réussi : {filename}"
        },
        "zh": {
            "source": "源文件:",
            "target": "目标文件:",
            "browse": "浏览...",
            "convert": "转换",
            "repair": "修复视频",
            "info": "显示视频信息",
            "extract_audio": "提取音频",
            "split_video": "拆分视频",
            "cut_segment": "剪切段",
            "download": "下载",
            "video_options": "视频选项:",
            "speed": "改变速度 (因子)",
            "mirror": "镜像视频",
            "split_duration": "拆分视频 (秒):",
            "audio_extract": "提取音频:",
            "segment_extract": "提取片段 / 开始时间和结束时间 (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "主要",
            "youtube_tab": "视频下载",
            "language_tab": "语言",
            "error_ffmpeg": "ffmpeg 或 ffprobe 不可用。请从以下网址安装 ffmpeg：",
            "error_download_ffmpeg": "下载和安装 ffmpeg 时出错：",
            "error_ffmpeg_command": "执行 ffmpeg 时出错：",
            "error_select_source_target": "请选择源和目标。",
            "error_extraction": "提取错误：",
            "success_conversion": "文件成功转换。",
            "success_repair": "视频成功复制（可能修复小错误）。",
            "success_segment": "段成功切割。",
            "success_audio_extraction": "音频成功提取。",
            "success_video_split": "视频成功分成 {num_segments} 部分。",
            "success_youtube_download": "YouTube 视频成功下载。",
            "error_video_duration": "无效的视频持续时间。",
            "error_split": "分割视频时出错：",
            "error_select_file": "请选择源文件。",
            "error_no_url": "请输入 URL。",
            "update_available": "有新版本({latest_version})可用。更改:\n{changes}\n\n你要更新吗?",
            "update_aborted": "更新已中止。",
            "success": "操作成功完成",
            "check_update": "检查更新",
            "info_tab": "信息",
            "error": "错误",
            "url": "网址",
            "success_download": "下载成功: {filename}"        
        },
        "ru": {
            "source": "Исходный файл:",
            "target": "Целевой файл:",
            "browse": "Обзор...",
            "convert": "Конвертировать",
            "repair": "Ремонт Видео",
            "info": "Показать информацию о видео",
            "extract_audio": "Извлечь аудио",
            "split_video": "Разделить видео",
            "cut_segment": "Вырезать сегмент",
            "download": "Скачать",
            "video_options": "Видео Опции:",
            "speed": "Изменить скорость (Фактор)",
            "mirror": "Отразить Видео",
            "split_duration": "Разделить видео (в секундах):",
            "audio_extract": "Извлечь аудио:",
            "segment_extract": "Вырезать сегмент / Время начала и окончания (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Основной",
            "youtube_tab": "Загрузка Видео",
            "language_tab": "Язык",
            "error_ffmpeg": "ffmpeg или ffprobe недоступны. Установите ffmpeg с:",
            "error_download_ffmpeg": "Ошибка загрузки и установки ffmpeg:",
            "error_ffmpeg_command": "Ошибка выполнения команды ffmpeg:",
            "error_select_source_target": "Пожалуйста, выберите источник и цель.",
            "error_extraction": "Ошибка извлечения:",
            "success_conversion": "Файл успешно конвертирован.",
            "success_repair": "Видео успешно скопировано (могут быть исправлены мелкие ошибки).",
            "success_segment": "Сегмент успешно вырезан.",
            "success_audio_extraction": "Аудио успешно извлечено.",
            "success_video_split": "Видео успешно разделено на {num_segments} частей.",
            "success_youtube_download": "Видео с YouTube успешно скачано.",
            "error_video_duration": "Недействительная продолжительность видео.",
            "error_split": "Ошибка разделения видео:",
            "error_select_file": "Пожалуйста, выберите исходный файл.",
            "error_no_url": "Пожалуйста, введите URL.",
            "update_available": "Доступна новая версия ({latest_version}). Изменения:\n{changes}\n\nХотите обновить?",
            "update_aborted": "Обновление было отменено.",
            "info_tab": "Информация",
            "check_update": "Проверить обновления",
            "success": "Операция успешно завершена",
            "error": "Ошибка",
            "url": "URL",
            "success_download": "Загрузка успешна: {filename}"
        },
        "hi": {
            "source": "स्रोत फ़ाइल:",
            "target": "लक्ष्य फ़ाइल:",
            "browse": "ब्राउज़ करें...",
            "convert": "कनवर्ट करें",
            "repair": "वीडियो ठीक करें",
            "info": "वीडियो जानकारी दिखाएं",
            "extract_audio": "ऑडियो निकालें",
            "split_video": "वीडियो विभाजित करें",
            "cut_segment": "सेगमेंट काटें",
            "download": "डाउनलोड",
            "video_options": "वीडियो विकल्प:",
            "speed": "गति बदलें (कारक)",
            "mirror": "वीडियो मिरर करें",
            "split_duration": "वीडियो विभाजित करें (सेकंड में):",
            "audio_extract": "ऑडियो निकालें:",
            "segment_extract": "खंड निकालें / प्रारंभ समय और समाप्ति समय (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "मुख्य",
            "youtube_tab": "वीडियो डाउनलोड",
            "language_tab": "भाषा",
            "error_ffmpeg": "ffmpeg या ffprobe उपलब्ध नहीं है। कृपया ffmpeg से स्थापित करें:",
            "error_download_ffmpeg": "ffmpeg डाउनलोड और इंस्टॉल करते समय त्रुटि:",
            "error_ffmpeg_command": "ffmpeg निष्पादित करते समय त्रुटि:",
            "error_select_source_target": "कृपया एक स्रोत और एक लक्ष्य चुनें।",
            "error_extraction": "निकालने में त्रुटि:",
            "success_conversion": "फ़ाइल सफलतापूर्वक कनवर्ट की गई।",
            "success_repair": "वीडियो सफलतापूर्वक कॉपी किया गया (छोटी त्रुटियों को ठीक किया जा सकता है)।",
            "success_segment": "सेगमेंट सफलतापूर्वक काटा गया।",
            "success_audio_extraction": "ऑडियो सफलतापूर्वक निकाला गया।",
            "success_video_split": "वीडियो सफलतापूर्वक {num_segments} भागों में विभाजित किया गया।",
            "success_youtube_download": "YouTube वीडियो सफलतापूर्वक डाउनलोड किया गया।",
            "error_video_duration": "अमान्य वीडियो अवधि।",
            "error_split": "वीडियो विभाजित करने में त्रुटि:",
            "error_select_file": "कृपया एक स्रोत फ़ाइल चुनें।",
            "error_no_url": "कृपया एक URL दर्ज करें।",
            "update_available": "एक नया संस्करण ({latest_version}) उपलब्ध है। परिवर्तन:\n{changes}\n\nक्या आप अपडेट करना चाहते हैं?",
            "update_aborted": "अपडेट रद्द कर दिया गया था।",
            "info_tab": "जानकारी",
            "check_update": "अपडेट की जाँच करें",
            "success": "ऑपरेशन सफलतापूर्वक पूरा हुआ",
            "error": "त्रुटि",
            "url": "URL",
            "success_download": "डाउनलोड सफल: {filename}"
        },
        "ja": {
            "source": "ソースファイル:",
            "target": "ターゲットファイル:",
            "browse": "参照...",
            "convert": "変換",
            "repair": "ビデオ修復",
            "info": "ビデオ情報を表示",
            "extract_audio": "音声を抽出",
            "split_video": "ビデオを分割",
            "cut_segment": "セグメントをカット",
            "download": "ダウンロード",
            "video_options": "ビデオオプション:",
            "speed": "速度を変更 (係数)",
            "mirror": "ビデオをミラー",
            "split_duration": "ビデオを分割 (秒):",
            "audio_extract": "音声を抽出:",
            "segment_extract": "セグメントを抽出 / 開始時間と終了時間 (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "メイン",
            "youtube_tab": "ビデオダウンロード",
            "language_tab": "言語",
            "error_ffmpeg": "ffmpeg または ffprobe が利用できません。以下から ffmpeg をインストールしてください：",
            "error_download_ffmpeg": "ffmpeg のダウンロードとインストール中にエラーが発生しました：",
            "error_ffmpeg_command": "ffmpeg を実行中にエラーが発生しました：",
            "error_select_source_target": "ソースとターゲットを選択してください。",
            "error_extraction": "抽出エラー：",
            "success_conversion": "ファイルが正常に変換されました。",
            "success_repair": "ビデオが正常にコピーされました（小さなエラーが修正される可能性があります）。",
            "success_segment": "セグメントが正常にカットされました。",
            "success_audio_extraction": "音声が正常に抽出されました。",
            "success_video_split": "ビデオが {num_segments} 部分に正常に分割されました。",
            "success_youtube_download": "YouTubeビデオが正常にダウンロードされました。",
            "error_video_duration": "無効なビデオの長さ。",
            "error_split": "ビデオの分割中にエラーが発生しました：",
            "error_select_file": "ソースファイルを選択してください。",
            "error_no_url": "URLを入力してください。",
            "update_available": "新しいバージョン（{latest_version}）が利用可能です。変更点：\n{changes}\n\n更新しますか？",
            "update_aborted": "更新が中止されました。",
            "info_tab": "情報",
            "check_update": "更新を確認する",
            "success": "操作が正常に完了しました",
            "error": "エラー",
            "url": "URL",
            "success_download": "ダウンロード成功: {filename}"        
        },
        "ar": {
            "source": "ملف المصدر:",
            "target": "ملف الهدف:",
            "browse": "تصفح...",
            "convert": "تحويل",
            "repair": "إصلاح الفيديو",
            "info": "عرض معلومات الفيديو",
            "extract_audio": "استخراج الصوت",
            "split_video": "تقسيم الفيديو",
            "cut_segment": "قص المقطع",
            "download": "تحميل",
            "video_options": "خيارات الفيديو:",
            "speed": "تغيير السرعة (العامل)",
            "mirror": "مرآة الفيديو",
            "split_duration": "تقسيم الفيديو (بالثواني):",
            "audio_extract": "استخراج الصوت:",
            "segment_extract": "استخراج المقطع / وقت البدء ووقت الانتهاء (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "الرئيسية",
            "youtube_tab": "تحميل فيديو",
            "language_tab": "اللغة",
            "error_ffmpeg": "ffmpeg أو ffprobe غير متاح. يرجى تثبيت ffmpeg من:",
            "error_download_ffmpeg": "خطأ في تنزيل وتثبيت ffmpeg:",
            "error_ffmpeg_command": "خطأ في تنفيذ ffmpeg:",
            "error_select_source_target": "الرجاء تحديد مصدر ووجهة.",
            "error_extraction": "خطأ في الاستخراج:",
            "success_conversion": "تم تحويل الملف بنجاح.",
            "success_repair": "تم نسخ الفيديو بنجاح (قد يتم إصلاح الأخطاء الصغيرة).",
            "success_segment": "تم قطع المقطع بنجاح.",
            "success_audio_extraction": "تم استخراج الصوت بنجاح.",
            "success_video_split": "تم تقسيم الفيديو بنجاح إلى {num_segments} أجزاء.",
            "success_youtube_download": "تم تنزيل فيديو YouTube بنجاح.",
            "error_video_duration": "مدة الفيديو غير صالحة.",
            "error_split": "خطأ في تقسيم الفيديو:",
            "error_select_file": "الرجاء تحديد ملف المصدر.",
            "error_no_url": "الرجاء إدخال عنوان URL.",
            "update_available": "الإصدار الجديد ({latest_version}) متاح. التغييرات:\n{changes}\n\nهل تريد التحديث?",
            "update_aborted": "تم إلغاء التحديث.",
            "info_tab": "معلومات",
            "check_update": "تحقق من التحديثات",
            "success": "اكتملت العملية بنجاح",
            "error": "خطأ",
            "url": "عنوان URL",
            "success_download": "تم التنزيل بنجاح: {filename}"        
        },
        "pt": {
            "source": "Arquivo Fonte:",
            "target": "Arquivo Alvo:",
            "browse": "Procurar...",
            "convert": "Converter",
            "repair": "Reparar Vídeo",
            "info": "Mostrar Informações do Vídeo",
            "extract_audio": "Extrair Áudio",
            "split_video": "Dividir Vídeo",
            "cut_segment": "Cortar Segmento",
            "download": "Baixar",
            "video_options": "Opções de Vídeo:",
            "speed": "Alterar Velocidade (Fator)",
            "mirror": "Espelhar Vídeo",
            "split_duration": "Dividir Vídeo (em segundos):",
            "audio_extract": "Extrair Áudio:",
            "segment_extract": "Extrair Segmento / Hora de Início e Hora de Término (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Principal",
            "youtube_tab": "Download de Vídeo",
            "language_tab": "Idioma",
            "error_ffmpeg": "ffmpeg ou ffprobe não está disponível. Instale o ffmpeg de:",
            "error_download_ffmpeg": "Erro ao baixar e instalar o ffmpeg:",
            "error_ffmpeg_command": "Erro ao executar o ffmpeg:",
            "error_select_source_target": "Selecione uma fonte e um destino.",
            "error_extraction": "Erro ao extrair:",
            "success_conversion": "Arquivo convertido com sucesso.",
            "success_repair": "Vídeo copiado com sucesso (pequenos erros podem ser corrigidos).",
            "success_segment": "Segmento cortado com sucesso.",
            "success_audio_extraction": "Áudio extraído com sucesso.",
            "success_video_split": "Vídeo dividido com sucesso em {num_segments} partes.",
            "success_youtube_download": "Vídeo do YouTube baixado com sucesso.",
            "error_video_duration": "Duração do vídeo inválida.",
            "error_split": "Erro ao dividir o vídeo:",
            "error_select_file": "Selecione um arquivo fonte.",
            "error_no_url": "Digite um URL.",
            "update_available": "Uma nova versão ({latest_version}) está disponível. Alterações:\n{changes}\n\nVocê quer atualizar?",
            "update_aborted": "A atualização foi abortada.",
            "info_tab": "Informação",
            "check_update": "Verificar atualizações",
            "success": "Operação concluída com sucesso",
            "error": "Erro",
            "url": "URL",
            "success_download": "Download bem-sucedido: {filename}"
        },
        "ko": {
            "source": "소스 파일:",
            "target": "대상 파일:",
            "browse": "탐색...",
            "convert": "변환",
            "repair": "비디오 수리",
            "info": "비디오 정보 표시",
            "extract_audio": "오디오 추출",
            "split_video": "비디오 분할",
            "cut_segment": "구간 자르기",
            "download": "다운로드",
            "video_options": "비디오 옵션:",
            "speed": "속도 변경 (비율)",
            "mirror": "비디오 미러링",
            "split_duration": "비디오 분할 (초 단위):",
            "audio_extract": "오디오 추출:",
            "segment_extract": "구간 추출 / 시작 시간 및 종료 시간 (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "메인",
            "youtube_tab": "비디오 다운로드",
            "language_tab": "언어",
            "error_ffmpeg": "ffmpeg 또는 ffprobe를 사용할 수 없습니다. 다음에서 ffmpeg를 설치하십시오:",
            "error_download_ffmpeg": "ffmpeg 다운로드 및 설치 오류:",
            "error_ffmpeg_command": "ffmpeg 실행 오류:",
            "error_select_source_target": "출처 및 대상을 선택하십시오.",
            "error_extraction": "추출 오류:",
            "success_conversion": "파일이 성공적으로 변환되었습니다.",
            "success_repair": "비디오가 성공적으로 복사되었습니다 (작은 오류가 수정될 수 있습니다).",
            "success_segment": "구간이 성공적으로 잘렸습니다.",
            "success_audio_extraction": "오디오가 성공적으로 추출되었습니다.",
            "success_video_split": "비디오가 {num_segments} 부분으로 성공적으로 분할되었습니다.",
            "success_youtube_download": "YouTube 비디오가 성공적으로 다운로드되었습니다.",
            "error_video_duration": "유효하지 않은 비디오 기간.",
            "error_split": "비디오 분할 오류:",
            "error_select_file": "출처 파일을 선택하십시오.",
            "error_no_url": "URL을 입력하십시오.",
            "update_available": "새 버전({latest_version})을 사용할 수 있습니다. 변경 사항:\n{changes}\n\n업데이트하시겠습니까?",
            "update_aborted": "업데이트가 중단되었습니다.",
            "info_tab": "정보",
            "check_update": "업데이트 확인",
            "success": "작업이 성공적으로 완료되었습니다",
            "error": "오류",
            "url": "URL",
            "success_download": "다운로드 성공: {filename}"
        },
        "da": {
            "source": "Kilde fil:",
            "target": "Mål fil:",
            "browse": "Gennemse...",
            "convert": "Konverter",
            "repair": "Reparer video",
            "info": "Vis videooplysninger",
            "extract_audio": "Ekstraher lyd",
            "split_video": "Opdel video",
            "cut_segment": "Klip segment",
            "download": "Download",
            "video_options": "Video muligheder:",
            "speed": "Ændr hastighed (faktor)",
            "mirror": "Spejl video",
            "split_duration": "Opdel video (i sekunder):",
            "audio_extract": "Ekstraher lyd:",
            "segment_extract": "Ekstraher segment / Starttid og sluttid (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Hoved",
            "youtube_tab": "Video Download",
            "language_tab": "Sprog",
            "error_ffmpeg": "ffmpeg eller ffprobe er ikke tilgængelig. Installer ffmpeg fra:",
            "error_download_ffmpeg": "Fejl ved download og installation af ffmpeg:",
            "error_ffmpeg_command": "Fejl ved udførelse af ffmpeg:",
            "error_select_source_target": "Vælg en kilde og et mål.",
            "error_extraction": "Fejl ved udtrækning:",
            "success_conversion": "Filen blev konverteret med succes.",
            "success_repair": "Videoen blev kopieret med succes (små fejl kan være rettet).",
            "success_segment": "Segmentet blev klippet med succes.",
            "success_audio_extraction": "Lyd blev udtrukket med succes.",
            "success_video_split": "Videoen blev opdelt i {num_segments} dele med succes.",
            "success_youtube_download": "YouTube-video blev downloadet med succes.",
            "error_video_duration": "Ugyldig videovarighed.",
            "error_split": "Fejl ved opdeling af video:",
            "error_select_file": "Vælg en kildefil.",
            "error_no_url": "Indtast en URL.",
            "update_available": "En ny version ({latest_version}) er tilgængelig. Ændringer:\n{changes}\n\nVil du opdatere?",
            "update_aborted": "Opdateringen blev afbrudt.",
            "info_tab": "Info",
            "check_update": "Tjek for opdateringer",
            "success": "Operationen blev gennemført med succes",
            "error": "Fejl",
            "url": "URL",
            "success_download": "Download lykkedes: {filename}"
        },
        "nl": {
            "source": "Bronbestand:",
            "target": "Doelbestand:",
            "browse": "Bladeren...",
            "convert": "Converteren",
            "repair": "Repareer video",
            "info": "Toon video-informatie",
            "extract_audio": "Audio extraheren",
            "split_video": "Video splitsen",
            "cut_segment": "Segment knippen",
            "download": "Downloaden",
            "video_options": "Video-opties:",
            "speed": "Verander snelheid (factor)",
            "mirror": "Spiegel Video",
            "split_duration": "Video splitsen (in seconden):",
            "audio_extract": "Audio extraheren:",
            "segment_extract": "Segment extraheren / Starttijd en eindtijd (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Hoofd",
            "youtube_tab": "Video Download",
            "language_tab": "Taal",
            "error_ffmpeg": "ffmpeg of ffprobe is niet beschikbaar. Installeer ffmpeg van:",
            "error_download_ffmpeg": "Fout bij het downloaden en installeren van ffmpeg:",
            "error_ffmpeg_command": "Fout bij het uitvoeren van ffmpeg:",
            "error_select_source_target": "Selecteer een bron en een doel.",
            "error_extraction": "Fout bij het extraheren:",
            "success_conversion": "Bestand succesvol geconverteerd.",
            "success_repair": "Video succesvol gekopieerd (kleine fouten kunnen zijn verholpen).",
            "success_segment": "Segment succesvol geknipt.",
            "success_audio_extraction": "Audio succesvol geëxtraheerd.",
            "success_video_split": "Video succesvol gesplitst in {num_segments} delen.",
            "success_youtube_download": "YouTube-video succesvol gedownload.",
            "error_video_duration": "Ongeldige videoduur.",
            "error_split": "Fout bij het splitsen van de video:",
            "error_select_file": "Selecteer een bronbestand.",
            "error_no_url": "Voer een URL in.",
            "update_available": "Er is een nieuwe versie ({latest_version}) beschikbaar. Wijzigingen:\n{changes}\n\nWilt u updaten?",
            "update_aborted": "De update is afgebroken.",
            "info_tab": "Informatie",
            "check_update": "Controleer op updates",
            "success": "Bewerking succesvol voltooid",
            "error": "Fout",
            "url": "URL",
            "success_download": "Download succesvol: {filename}"
        },
        "pl": {
            "source": "Plik źródłowy:",
            "target": "Plik docelowy:",
            "browse": "Przeglądaj...",
            "convert": "Konwertuj",
            "repair": "Napraw wideo",
            "info": "Pokaż informacje o wideo",
            "extract_audio": "Wyodrębnij dźwięk",
            "split_video": "Podziel wideo",
            "cut_segment": "Wytnij segment",
            "download": "Pobierz",
            "video_options": "Opcje wideo:",
            "speed": "Zmień prędkość (współczynnik)",
            "mirror": "Lustro wideo",
            "split_duration": "Podziel wideo (w sekundach):",
            "audio_extract": "Wyodrębnij dźwięk:",
            "segment_extract": "Wyodrębnij segment / Czas rozpoczęcia i zakończenia (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Główny",
            "youtube_tab": "Video Pobieranie",
            "language_tab": "Język",
            "error_ffmpeg": "ffmpeg lub ffprobe nie jest dostępne. Zainstaluj ffmpeg z:",
            "error_download_ffmpeg": "Błąd podczas pobierania i instalacji ffmpeg:",
            "error_ffmpeg_command": "Błąd podczas wykonywania ffmpeg:",
            "error_select_source_target": "Wybierz źródło i cel.",
            "error_extraction": "Błąd podczas wyodrębniania:",
            "success_conversion": "Plik pomyślnie przekonwertowany.",
            "success_repair": "Wideo pomyślnie skopiowane (małe błędy mogą być naprawione).",
            "success_segment": "Segment pomyślnie wycięty.",
            "success_audio_extraction": "Dźwięk pomyślnie wyodrębniony.",
            "success_video_split": "Wideo pomyślnie podzielone na {num_segments} części.",
            "success_youtube_download": "Wideo z YouTube pomyślnie pobrane.",
            "error_video_duration": "Nieprawidłowy czas trwania wideo.",
            "error_split": "Błąd podczas podziału wideo:",
            "error_select_file": "Wybierz plik źródłowy.",
            "error_no_url": "Wprowadź URL.",
            "update_available": "Dostępna jest nowa wersja ({latest_version}). Zmiany:\n{changes}\n\nCzy chcesz zaktualizować?",
            "update_aborted": "Aktualizacja została przerwana.",
            "info_tab": "Informacja",
            "check_update": "Sprawdź aktualizacje",
            "success": "Operacja zakończona pomyślnie",
            "error": "Błąd",
            "url": "URL",
            "success_download": "Pobieranie zakończone sukcesem: {filename}"
        },
        "no": {
            "source": "Kilde fil:",
            "target": "Mål fil:",
            "browse": "Bla gjennom...",
            "convert": "Konverter",
            "repair": "Reparer video",
            "info": "Vis video informasjon",
            "extract_audio": "Ekstraher lyd",
            "split_video": "Del video",
            "cut_segment": "Klipp segment",
            "download": "Last ned",
            "video_options": "Videoalternativer:",
            "speed": "Endre hastighet (faktor)",
            "mirror": "Speilvideo",
            "split_duration": "Del video (i sekunder):",
            "audio_extract": "Ekstraher lyd:",
            "segment_extract": "Ekstraher segment / Starttid og sluttid (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Hoved",
            "youtube_tab": "Video-nedlasting",
            "language_tab": "Språk",
            "error_ffmpeg": "ffmpeg eller ffprobe er ikke tilgjengelig. Installer ffmpeg fra:",
            "error_download_ffmpeg": "Feil ved nedlasting og installasjon av ffmpeg:",
            "error_ffmpeg_command": "Feil ved kjøring av ffmpeg:",
            "error_select_source_target": "Velg en kilde og et mål.",
            "error_extraction": "Feil ved ekstraksjon:",
            "success_conversion": "Filen ble konvertert med hell.",
            "success_repair": "Videoen ble kopiert med hell (små feil kan bli rettet).",
            "success_segment": "Segmentet ble kuttet med hell.",
            "success_audio_extraction": "Lyd ble ekstrahert med hell.",
            "success_video_split": "Videoen ble delt inn i {num_segments} deler med hell.",
            "success_youtube_download": "YouTube-video ble lastet ned med hell.",
            "error_video_duration": "Ugyldig videovarighet.",
            "error_split": "Feil ved deling av video:",
            "error_select_file": "Velg en kildefil.",
            "error_no_url": "Skriv inn en URL.",
            "update_available": "En ny versjon ({latest_version}) er tilgjengelig. Endringer:\n{changes}\n\nVil du oppdatere?",
            "update_aborted": "Oppdateringen ble avbrutt.",
            "info_tab": "Info",
            "check_update": "Sjekk etter oppdateringer",
            "success": "Operasjonen ble fullført med suksess",
            "error": "Feil",
            "url": "URL",
            "success_download": "Nedlasting vellykket: {filename}"
        },
        "fi": {
            "source": "Lähdetiedosto:",
            "target": "Kohdetiedosto:",
            "browse": "Selaa...",
            "convert": "Muunna",
            "repair": "Korjaa video",
            "info": "Näytä videon tiedot",
            "extract_audio": "Pura ääni",
            "split_video": "Jaa video",
            "cut_segment": "Leikkaa segmentti",
            "download": "Lataa",
            "video_options": "Videon vaihtoehdot:",
            "speed": "Muuta nopeutta (kerroin)",
            "mirror": "Peili Video",
            "split_duration": "Jaa video (sekunneissa):",
            "audio_extract": "Pura ääni:",
            "segment_extract": "Pura segmentti / Aloitusaika ja lopetusaika (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Pää",
            "youtube_tab": "Video Lataus",
            "language_tab": "Kieli",
            "error_ffmpeg": "ffmpeg tai ffprobe ei ole käytettävissä. Asenna ffmpeg osoitteesta:",
            "error_download_ffmpeg": "Virhe ladattaessa ja asennettaessa ffmpeg:",
            "error_ffmpeg_command": "Virhe suoritettaessa ffmpeg:",
            "error_select_source_target": "Valitse lähde ja kohde.",
            "error_extraction": "Virhe purkamisessa:",
            "success_conversion": "Tiedosto muunnettiin onnistuneesti.",
            "success_repair": "Video kopioitiin onnistuneesti (pienet virheet voidaan korjata).",
            "success_segment": "Segmentti leikattiin onnistuneesti.",
            "success_audio_extraction": "Ääni purettiin onnistuneesti.",
            "success_video_split": "Video jaettiin onnistuneesti {num_segments} osaan.",
            "success_youtube_download": "YouTube-video ladattiin onnistuneesti.",
            "error_video_duration": "Virheellinen videon kesto.",
            "error_split": "Virhe jaettaessa videota:",
            "error_select_file": "Valitse lähdetiedosto.",
            "error_no_url": "Syötä URL.",
            "update_available": "Uusi versio ({latest_version}) on saatavilla. Muutokset:\n{changes}\n\nHaluatko päivittää?",
            "update_aborted": "Päivitys keskeytettiin.",
            "info_tab": "Info",
            "check_update": "Tarkista päivitykset",
            "success": "Toiminto suoritettiin onnistuneesti",
            "error": "Virhe",
            "url": "URL",
            "success_download": "Lataus onnistui: {filename}"
        },
        "tr": {
            "source": "Kaynak Dosya:",
            "target": "Hedef Dosya:",
            "browse": "Gözat...",
            "convert": "Dönüştür",
            "repair": "Videoyu Onar",
            "info": "Video Bilgilerini Göster",
            "extract_audio": "Sesi Çıkart",
            "split_video": "Videoyu Böl",
            "cut_segment": "Segmenti Kes",
            "download": "İndir",
            "video_options": "Video Seçenekleri:",
            "speed": "Hızı Değiştir (Faktör)",
            "mirror": "Ayna Video",
            "split_duration": "Videoyu Böl (saniye olarak):",
            "audio_extract": "Sesi Çıkart:",
            "segment_extract": "Segmenti Çıkart / Başlangıç ve Bitiş Saati (SS:DD:SS):",
            "from_to": " <-> ",
            "main_tab": "Ana",
            "youtube_tab": "Video İndir",
            "language_tab": "Dil",
            "error_ffmpeg": "ffmpeg veya ffprobe kullanılamıyor. ffmpeg'i buradan yükleyin:",
            "error_download_ffmpeg": "ffmpeg indirme ve yükleme hatası:",
            "error_ffmpeg_command": "ffmpeg çalıştırma hatası:",
            "error_select_source_target": "Bir kaynak ve hedef seçin.",
            "error_extraction": "Çıkartma hatası:",
            "success_conversion": "Dosya başarıyla dönüştürüldü.",
            "success_repair": "Video başarıyla kopyalandı (küçük hatalar düzeltilebilir).",
            "success_segment": "Segment başarıyla kesildi.",
            "success_audio_extraction": "Ses başarıyla çıkartıldı.",
            "success_video_split": "Video başarıyla {num_segments} parçaya bölündü.",
            "success_youtube_download": "YouTube videosu başarıyla indirildi.",
            "error_video_duration": "Geçersiz video süresi.",
            "error_split": "Video bölme hatası:",
            "error_select_file": "Bir kaynak dosya seçin.",
            "error_no_url": "Bir URL girin.",
            "update_available": "Yeni bir sürüm ({latest_version}) mevcut. Değişiklikler:\n{changes}\n\nGüncellemek istiyor musunuz?",
            "update_aborted": "Güncelleme iptal edildi.",
            "info_tab": "Bilgi",
            "check_update": "Güncellemeleri kontrol et",
            "success": "İşlem başarıyla tamamlandı",
            "error": "Hata",
            "url": "URL",
            "success_download": "İndirme başarılı: {filename}"
        },
        "sv": {
            "source": "Källfil:",
            "target": "Målfil:",
            "browse": "Bläddra...",
            "convert": "Konvertera",
            "repair": "Reparera video",
            "info": "Visa videoinformation",
            "extract_audio": "Extrahera ljud",
            "split_video": "Dela video",
            "cut_segment": "Klipp segment",
            "download": "Ladda ner",
            "video_options": "Videoalternativ:",
            "speed": "Ändra hastighet (faktor)",
            "mirror": "Spegel video",
            "split_duration": "Dela video (i sekunder):",
            "audio_extract": "Extrahera ljud:",
            "segment_extract": "Extrahera segment / Starttid och sluttid (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Huvud",
            "youtube_tab": "Video Nedladdning",
            "language_tab": "Språk",
            "error_ffmpeg": "ffmpeg eller ffprobe är inte tillgängligt. Installera ffmpeg från:",
            "error_download_ffmpeg": "Fel vid nedladdning och installation av ffmpeg:",
            "error_ffmpeg_command": "Fel vid körning av ffmpeg:",
            "error_select_source_target": "Välj en källa och ett mål.",
            "error_extraction": "Fel vid extraktion:",
            "success_conversion": "Filen konverterades framgångsrikt.",
            "success_repair": "Videon kopierades framgångsrikt (små fel kan ha rättats).",
            "success_segment": "Segmentet klipptes framgångsrikt.",
            "success_audio_extraction": "Ljud extraherades framgångsrikt.",
            "success_video_split": "Videon delades framgångsrikt i {num_segments} delar.",
            "success_youtube_download": "YouTube-video laddades ner framgångsrikt.",
            "error_video_duration": "Ogiltig videolängd.",
            "error_split": "Fel vid delning av video:",
            "error_select_file": "Välj en källfil.",
            "error_no_url": "Ange en URL.",
            "update_available": "En ny version ({latest_version}) är tillgänglig. Ändringar:\n{changes}\n\nVill du uppdatera?",
            "update_aborted": "Uppdateringen avbröts.",
            "info_tab": "Information",
            "check_update": "Kontrollera uppdateringar",
            "success": "Åtgärden genomfördes framgångsrikt",
            "error": "Fel",
            "url": "URL",
            "success_download": "Nedladdning lyckades: {filename}"
        },
        "el": {
            "source": "Αρχείο Πηγής:",
            "target": "Αρχείο Προορισμού:",
            "browse": "Περιήγηση...",
            "convert": "Μετατροπή",
            "repair": "Επιδιόρθωση Βίντεο",
            "info": "Εμφάνιση Πληροφοριών Βίντεο",
            "extract_audio": "Εξαγωγή Ήχου",
            "split_video": "Διαίρεση Βίντεο",
            "cut_segment": "Κοπή Τμήματος",
            "download": "Λήψη",
            "video_options": "Επιλογές Βίντεο:",
            "speed": "Αλλαγή Ταχύτητας (Συντελεστής)",
            "mirror": "Καθρέπτης Βίντεο",
            "split_duration": "Διαίρεση Βίντεο (σε δευτερόλεπτα):",
            "audio_extract": "Εξαγωγή Ήχου:",
            "segment_extract": "Εξαγωγή Τμήματος / Ώρα Έναρξης και Λήξης (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Κύρια",
            "youtube_tab": "Λήψη Βίντεο",
            "language_tab": "Γλώσσα",
            "error_ffmpeg": "Το ffmpeg ή το ffprobe δεν είναι διαθέσιμο. Εγκαταστήστε το ffmpeg από:",
            "error_download_ffmpeg": "Σφάλμα κατά τη λήψη και εγκατάσταση του ffmpeg:",
            "error_ffmpeg_command": "Σφάλμα κατά την εκτέλεση του ffmpeg:",
            "error_select_source_target": "Επιλέξτε μια πηγή και έναν προορισμό.",
            "error_extraction": "Σφάλμα κατά την εξαγωγή:",
            "success_conversion": "Το αρχείο μετατράπηκε με επιτυχία.",
            "success_repair": "Το βίντεο αντιγράφηκε με επιτυχία (μικρά σφάλματα μπορεί να διορθώθηκαν).",
            "success_segment": "Το τμήμα κόπηκε με επιτυχία.",
            "success_audio_extraction": "Ο ήχος εξήχθη με επιτυχία.",
            "success_video_split": "Το βίντεο χωρίστηκε επιτυχώς σε {num_segments} μέρη.",
            "success_youtube_download": "Το βίντεο από το YouTube κατέβηκε με επιτυχία.",
            "error_video_duration": "Μη έγκυρη διάρκεια βίντεο.",
            "error_split": "Σφάλμα κατά τον διαχωρισμό του βίντεο:",
            "error_select_file": "Επιλέξτε ένα αρχείο πηγής.",
            "error_no_url": "Εισαγάγετε ένα URL.",
            "update_available": "Μια νέα έκδοση ({latest_version}) είναι διαθέσιμη. Αλλαγές:\n{changes}\n\nΘέλετε να ενημερώσετε?",
            "update_aborted": "Η ενημέρωση ακυρώθηκε.",
            "info_tab": "Πληροφορίες",
            "check_update": "Έλεγχος για ενημερώσεις",
            "success": "Η λειτουργία ολοκληρώθηκε με επιτυχία",
            "error": "Σφάλμα",
            "url": "URL",
            "success_download": "Η λήψη ήταν επιτυχής: {filename}"
        },
        "he": {
            "source": "קובץ מקור:",
            "target": "קובץ יעד:",
            "browse": "עיון...",
            "convert": "המר",
            "repair": "תקן וידאו",
            "info": "הצג מידע על הווידאו",
            "extract_audio": "חלץ אודיו",
            "split_video": "פצל וידאו",
            "cut_segment": "חתוך קטע",
            "download": "הורד",
            "video_options": "אפשרויות וידאו:",
            "speed": "שנה מהירות (פקטור)",
            "mirror": "מראה וידאו",
            "split_duration": "פצל וידאו (בשניות):",
            "audio_extract": "חלץ אודיו:",
            "segment_extract": "חלץ קטע / זמן התחלה וזמן סיום (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "ראשי",
            "youtube_tab": "הורדת וידאו",
            "language_tab": "שפה",
            "error_ffmpeg": "ffmpeg או ffprobe אינם זמינים. התקן את ffmpeg מ:",
            "error_download_ffmpeg": "שגיאה בהורדה ובהתקנה של ffmpeg:",
            "error_ffmpeg_command": "שגיאה בהפעלת ffmpeg:",
            "error_select_source_target": "בחר מקור ויעד.",
            "error_extraction": "שגיאה בחילוץ:",
            "success_conversion": "הקובץ הומר בהצלחה.",
            "success_repair": "הווידאו הועתק בהצלחה (שגיאות קטנות עשויות להיות מתוקנות).",
            "success_segment": "הקטע נחתך בהצלחה.",
            "success_audio_extraction": "האודיו חולץ בהצלחה.",
            "success_video_split": "הווידאו פוצל בהצלחה ל-{num_segments} חלקים.",
            "success_youtube_download": "הווידאו מיוטיוב הורד בהצלחה.",
            "error_video_duration": "משך וידאו לא חוקי.",
            "error_split": "שגיאה בפיצול הווידאו:",
            "error_select_file": "בחר קובץ מקור.",
            "error_no_url": "הזן כתובת URL.",
            "update_available": "גרסה חדשה ({latest_version}) זמינה. שינויים:\n{changes}\n\nהאם ברצונך לעדכן?",
            "update_aborted": "העדכון בוטל.",
            "info_tab": "מידע",
            "check_update": "בדוק עדכונים",
            "success": "הפעולה הושלמה בהצלחה",
            "error": "שגיאה",
            "url": "כתובת URL",
            "success_download": "ההורדה הצליחה: {filename}"
        },
        "hu": {
            "source": "Forrás fájl:",
            "target": "Cél fájl:",
            "browse": "Tallózás...",
            "convert": "Átalakítás",
            "repair": "Videó javítása",
            "info": "Videó információk megjelenítése",
            "extract_audio": "Hang kinyerése",
            "split_video": "Videó felosztása",
            "cut_segment": "Szegmens vágása",
            "download": "Letöltés",
            "video_options": "Videó beállítások:",
            "speed": "Sebesség változtatása (arány)",
            "mirror": "Videó tükrözése",
            "split_duration": "Videó felosztása (másodpercben):",
            "audio_extract": "Hang kinyerése:",
            "segment_extract": "Szegmens kinyerése / Kezdési és befejezési idő (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Fő",
            "youtube_tab": "Videó Letöltés",
            "language_tab": "Nyelv",
            "error_ffmpeg": "Az ffmpeg vagy az ffprobe nem elérhető. Telepítse az ffmpeg-et innen:",
            "error_download_ffmpeg": "Hiba az ffmpeg letöltése és telepítése közben:",
            "error_ffmpeg_command": "Hiba az ffmpeg futtatása közben:",
            "error_select_source_target": "Válasszon forrást és célt.",
            "error_extraction": "Hiba a kinyerés során:",
            "success_conversion": "A fájl sikeresen átalakítva.",
            "success_repair": "A videó sikeresen másolva (kisebb hibák javíthatók).",
            "success_segment": "A szegmens sikeresen vágva.",
            "success_audio_extraction": "A hang sikeresen kinyerve.",
            "success_video_split": "A videó sikeresen felosztva {num_segments} részre.",
            "success_youtube_download": "A YouTube videó sikeresen letöltve.",
            "error_video_duration": "Érvénytelen videó hossz.",
            "error_split": "Hiba a videó felosztása közben:",
            "error_select_file": "Válasszon egy forrásfájlt.",
            "error_no_url": "Adjon meg egy URL-t.",
            "update_available": "Egy új verzió ({latest_version}) elérhető. Változások:\n{changes}\n\nSzeretné frissíteni?",
            "update_aborted": "A frissítés megszakítva.",
            "info_tab": "Információ",
            "check_update": "Frissítések keresése",
            "success": "A művelet sikeresen befejeződött",
            "error": "Hiba",
            "url": "URL",
            "success_download": "Letöltés sikeres: {filename}"
        },
        "th": {
            "source": "ไฟล์ต้นทาง:",
            "target": "ไฟล์ปลายทาง:",
            "browse": "เรียกดู...",
            "convert": "แปลง",
            "repair": "ซ่อมวิดีโอ",
            "info": "แสดงข้อมูลวิดีโอ",
            "extract_audio": "แยกเสียง",
            "split_video": "แบ่งวิดีโอ",
            "cut_segment": "ตัดส่วน",
            "download": "ดาวน์โหลด",
            "video_options": "ตัวเลือกวิดีโอ:",
            "speed": "เปลี่ยนความเร็ว (ปัจจัย)",
            "mirror": "วิดีโอสะท้อน",
            "split_duration": "แบ่งวิดีโอ (เป็นวินาที):",
            "audio_extract": "แยกเสียง:",
            "segment_extract": "แยกส่วน / เวลาเริ่มต้นและเวลาสิ้นสุด (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "หลัก",
            "youtube_tab": "ดาวน์โหลดวิดีโอ",
            "language_tab": "ภาษา",
            "error_ffmpeg": "ffmpeg หรือ ffprobe ไม่พร้อมใช้งาน โปรดติดตั้ง ffmpeg จาก:",
            "error_download_ffmpeg": "เกิดข้อผิดพลาดในการดาวน์โหลดและติดตั้ง ffmpeg:",
            "error_ffmpeg_command": "เกิดข้อผิดพลาดในการเรียกใช้ ffmpeg:",
            "error_select_source_target": "โปรดเลือกต้นทางและปลายทาง",
            "error_extraction": "เกิดข้อผิดพลาดในการแยก:",
            "success_conversion": "ไฟล์แปลงสำเร็จแล้ว",
            "success_repair": "วิดีโอก็อปปี้สำเร็จแล้ว (อาจแก้ไขข้อผิดพลาดเล็กน้อย)",
            "success_segment": "ส่วนตัดสำเร็จแล้ว",
            "success_audio_extraction": "แยกเสียงสำเร็จแล้ว",
            "success_video_split": "แบ่งวิดีโอสำเร็จแล้วเป็น {num_segments} ส่วน",
            "success_youtube_download": "ดาวน์โหลดวิดีโอ YouTube สำเร็จแล้ว",
            "error_video_duration": "ระยะเวลาวิดีโอไม่ถูกต้อง",
            "error_split": "เกิดข้อผิดพลาดในการแบ่งวิดีโอ:",
            "error_select_file": "โปรดเลือกไฟล์ต้นทาง",
            "error_no_url": "โปรดใส่ URL",
            "update_available": "มีเวอร์ชันใหม่ ({latest_version}) พร้อมใช้งาน การเปลี่ยนแปลง:\n{changes}\n\nคุณต้องการอัปเดตหรือไม่?",
            "update_aborted": "ยกเลิกการอัปเดตแล้ว",
            "info_tab": "ข้อมูล",
            "check_update": "ตรวจสอบการอัปเดต",
            "success": "ดำเนินการสำเร็จ",
            "error": "ข้อผิดพลาด",
            "url": "URL",
            "success_download": "ดาวน์โหลดสำเร็จ: {filename}"
        },
        "es_ar": {
            "source": "Archivo Fuente:",
            "target": "Archivo Destino:",
            "browse": "Buscar...",
            "convert": "Convertir",
            "repair": "Reparar Video",
            "info": "Mostrar Información del Video",
            "extract_audio": "Extraer Audio",
            "split_video": "Dividir Video",
            "cut_segment": "Cortar Segmento",
            "download": "Descargar",
            "video_options": "Opciones de Video:",
            "speed": "Cambiar Velocidad (Factor)",
            "mirror": "Espejar Video",
            "split_duration": "Dividir Video (en segundos):",
            "audio_extract": "Extraer Audio:",
            "segment_extract": "Extraer Segmento / Hora de Inicio y Hora de Fin (HH:MM:SS):",
            "from_to": " <-> ",
            "main_tab": "Principal",
            "youtube_tab": "Descarga de Video",
            "language_tab": "Idioma",
            "error_ffmpeg": "ffmpeg o ffprobe no está disponible. Instale ffmpeg desde:",
            "error_download_ffmpeg": "Error al descargar e instalar ffmpeg:",
            "error_ffmpeg_command": "Error al ejecutar ffmpeg:",
            "error_select_source_target": "Seleccione una fuente y un destino.",
            "error_extraction": "Error al extraer:",
            "success_conversion": "Archivo convertido con éxito.",
            "success_repair": "Video copiado con éxito (se pueden corregir pequeños errores).",
            "success_segment": "Segmento cortado con éxito.",
            "success_audio_extraction": "Audio extraído con éxito.",
            "success_video_split": "Video dividido con éxito en {num_segments} partes.",
            "success_youtube_download": "Video de YouTube descargado con éxito.",
            "error_video_duration": "Duración de video no válida.",
            "error_split": "Error al dividir el video:",
            "error_select_file": "Seleccione un archivo fuente.",
            "error_no_url": "Ingrese una URL.",
            "update_available": "Una nueva versión ({latest_version}) está disponible. Cambios:\n{changes}\n\n¿Quieres actualizar?",
            "update_aborted": "La actualización fue abortada.",
            "info_tab": "Información",
            "check_update": "Buscar actualizaciones",
            "success": "Operación completada con éxito",
            "error": "Error",
            "url": "URL",
            "success_download": "Descarga exitosa: {filename}"
        }
    }

    return translations.get(language, translations["en"])
